spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://39.105.111.19:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
    # 防止mysql 空闲断开连接
      initial-size: 5
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 30000
      

# 配置mybatis
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
#  配置mybatis type的别名
  type-aliases-package: priv.geekjoker.joy.blog.vo

server:
  port: 8080


logging:
  level:
    ROOT: INFO
    priv.geekjoker.joy.blog: DEBUG
  file:
    name: target/app.log

